### ISSUE TITLE
Schema 'mode' is not specified

### ISSUE THREAD

**Issue by efel85** [efel85/TOMP-API#1]
No further specification available besides:

   **mode:**
      description: The type of the leg MaaS uses to identify the leg

(from Vincent Mastenbroek via email)

**Comment by efel85** [comment]
Described in MaaS-vocabulary for use in the data string, together with an energy label

**Comment by efel85** [comment]
**Suggestion from Asset Data spec v0.9:**
Walk 
Bike
Moped
Scooter (step)
Segway
Car
Taxi
Public bus
Coach bus
Office bus
Tram
Lightrail/metro 
Train
Ferry
Water-taxi
Water-bus 
Private charter airline
Public airline/charter

**Comment by ro5k0** [comment]
I would like to add Cargo Bike to the list.
