### ISSUE TITLE
Define overlap and re-use possibilities of Open Journey Planner

### ISSUE THREAD

**Issue by efel85** [efel85/TOMP-API#11]

**Comment by edwinvandenbelt** [comment]
Hello Eduardo, what do you mean 'Open Journey Planner': Open Trip Planner or the Finnish initiative?

**Comment by skinkie** [comment]
@edwinvandenbelt OpenJourneyPlanner or DistributedJourneyPlanner is a CEN standard that defines an B2B interface between journey planners to exchange travel information. The XSDs are available via https://github.com/VDVde/OJP . The documentation itself via NEN (or if you send me an e-mail...)

**Comment by edwinvandenbelt** [comment]
thnx!
