### ISSUE TITLE
Is the user id in the GTOAS the same as the AccountID in the MaaS Router

### ISSUE THREAD

**Issue by edwinvandenbelt** [efel85/TOMP-API#15]
Is the user id in the GTOAS the same as the AccountID in the MaaS Router?

**Comment by efel85** [comment]
Very probably. Need to align this with Accept Institute.

**Comment by efel85** [comment]
Answer to the question: yes. Accept Institute will issue unique AccountIDs for MSPs to apply to their users. But this is also related to the necessity for blacklisting, as a vandal could change MSP to continue traveling (and vandalizing) a TO-asset if no link is made between the AccountID and a specific user.

**Comment by efel85** [comment]
new issue #67 added for blacklisting facilities
