### ISSUE TITLE
Consequent formatting needed

### ISSUE THREAD

**Issue by edwinvandenbelt** [efel85/TOMP-API#23]
different casing, inconsequent usage of enums, not every object has his own file, etc. etc. 
Please repair

**Comment by paxx-dev** [comment]
@edwinvandenbelt Can this be closed now the pull request has been merged?

**Comment by edwinvandenbelt** [comment]
What's 'this' ? I don't have a context...

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by paxx-dev** [comment]
@edwinvandenbelt 'This' is issue #23: "Consequent formatting needed" on the TOMP-API GitHub. I'm assuming you got an email notification from it? You can see the context in issue #23 on GitHub.

To repeat the question including context: Can the issue you created about consequent formatting being needed be closed now that your pull request fixing (all?) of those problems has been merged?

**Comment by edwinvandenbelt** [comment]
Ok. This one can be closed, when accepted and I think we just did in the meeting of this morning.



Met vriendelijke groet, with kind regards,

Edwin van den Belt
Software architect

T +31 (0)570 666 221 | M +31 (0)6 20 957 905  | E evdbelt@dat.nl<mailto:evdbelt@dat.nl>

[cid:image001.png@01D3F8E2.49F2E9B0]
DAT.Mobility BV | Snipperlingsdijk 4 | 7417 BJ Deventer | The Netherlands | www.dat.nl<http://www.dat.nl/>

DAT Mobility is onderdeel van de Goudappel Groep. Wij werken vanuit Amsterdam, Den Haag, Deventer, Eindhoven, Leeuwarden en via partners in het buitenland.



Van: paxx-dev <notifications@github.com>
Verzonden: Wednesday, 26 June 2019 15:20
Aan: efel85/TOMP-API <TOMP-API@noreply.github.com>
CC: Edwin van den Belt <edwinvandenbelt@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [efel85/TOMP-API] Consequent formatting needed (#23)


@edwinvandenbelt<https://github.com/edwinvandenbelt> 'This' is issue #23<https://github.com/efel85/TOMP-API/issues/23>: "Consequent formatting needed" on the TOMP-API GitHub. I'm assuming you got an email notification from it? You can see the context in issue #23<https://github.com/efel85/TOMP-API/issues/23> on GitHub.

To repeat the question including context: Can the issue you created about consequent formatting being needed be closed now that your pull request fixing (all?) of those problems has been merged?
