### ISSUE TITLE
booking-options is missing return values

### ISSUE THREAD

**Issue by edwinvandenbelt** [efel85/TOMP-API#28]
The booking-option returns a possible leg, but doesn't tell 
a) what does it cost?
b) how likely it is you can make it really in the suggested time?
c) the overlays (for train/metro)
d) the amount of emission

**Comment by edwinvandenbelt** [comment]
In the available-option there is now a price, a leg, type-of-asset and optionally a specific asset. Overlays stays a problem (I don't know how e.g. NS will return a leg containing multiple parts.

**Comment by efel85** [comment]
To be included in Blueprint: changing an asset means starting a new leg. Might give issues with trains and ticketing. To be discussed in the future.

**Comment by efel85** [comment]
The only missing part is overlays, this has been opened as a new issue.
