### ISSUE TITLE
Communicate API-version to be used

### ISSUE THREAD

**Issue by pimmeh** [efel85/TOMP-API#29]
MaaS-providers and Transport Operators are not going to use the same TOMP-version at the same time. In essence, there will be no big bang moment that all the companies will switch to a newer version once we release it. I therefore suggest that we include a way that the version to be used in the communication is in the communication itself.

For instance, in each authentication handshake between MP and TO, the API-standard to be used is included in the header so that the receiving party know's what TOMP-version to communicate back and forth.

**Comment by efel85** [comment]
Suggestion to add the API-version in the header of each message that is exchanged. We need to specify the header for the communication.

**Comment by paxx-dev** [comment]
Solved in #48?

**Comment by efel85** [comment]
Yes, solved in #48
