### ISSUE TITLE
Update leg-geometry and lon-lat to lat-lon

### ISSUE THREAD

**Issue by skinkie** [efel85/TOMP-API#32]
Change lon-lat pairs to lat-lon pairs of numbers, in similar fashion as GeoJSON. leg-geometry might be updated to mimic a GeoJSON LineString / Polygon.

**Comment by paxx-dev** [comment]
For #18 I am replacing all occurrences of lat and lon fields with a ref to the coordinates object, so those do not need to be reordered, only those in the actual coordinates object, and leg-geometry if we want to change that to a more efficient format.

**Comment by edwinvandenbelt** [comment]
No, that's not what we desided this morning. The refs should be replace by type: number. Otherwise we have an object again, including the burden of the extra tokens to send....
So the result (json) should be: "lon": 3.5342, "lat": 55.3423

**Comment by ro5k0** [comment]
or "lat": 55.3423, "lon": 3.5342 ;-)

**Comment by edwinvandenbelt** [comment]
And leg-geometry should become something like this:

    leg-geometry:
      type: string
      example: LINESTRING((5.138795 52.388391, 5.267885 52.388391, 5.267885 52.343108, 5.138795 52.343108))

**Comment by edwinvandenbelt** [comment]
@Ross: json doesn't garantee the order of the properties....

**Comment by edwinvandenbelt** [comment]
But I know, we aggreed on this this morning ;-)

**Comment by paxx-dev** [comment]
Unless you want to remove _all_ uses of the coordinates object, these are two separate issues. Issue #18 is to fix the inconsistent use of either the coordinates object, or latitude and longitude on their own, not wrapped in an object. 
I understood the efficiency argument to apply primarily to the leg-geometry, which has many coordinates to hold. I think we should not try to optimise all fields for space efficiency.

**Comment by paxx-dev** [comment]
For example, compare the options-leg with station-information. The first uses the coordinates object for from and to locations, the other lat and lon directly. This is inconsistent, so unless we are not just removing the lat and lon objects but removing the coordinates object completely, this should be fixed, which is issue #18

**Comment by skinkie** [comment]
What is wrong with the following syntax?
```json
"coordinates": [
          [
            [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],
            [100.0, 1.0], [100.0, 0.0]
          ]
        ]
```

**Comment by paxx-dev** [comment]
Nothing per se. However, we now have the coordinates object in some places, and separate latitude and longitude in other places. 

I don't think we should have two different ways to represent a pair of coordinates, except in the leg-geometry case where a compact encoding makes sense.
