### ISSUE TITLE
Odd differences between booking options and new booking

### ISSUE THREAD

**Issue by paxx-dev** [efel85/TOMP-API#34]
When an MSP wants to know from the TO what options there are they request /bookings/options with some parameters related to the leg, which returns a schemas/options containing an array of schemas/leg and schemas/type-of-asset.
When an MSP makes a new booking, they do so by sending a schemas/new-booking which contains a schemas/leg which contains a schemas/mode.

This means that partially things are repeated between the two types of request - mode has some similarities with type-of-asset and the options parameters with the leg schema. The things that aren't repeated could be considered missing features, as mentioned in some issues listed below. For example, options returns very specific vehicle information in the type-of-asset, but it is impossible to book as specifically one vehicle type in the new booking, which only allows the more limited mode schema to define what to book.

I suggest the group that is looking at what schemas represent what also tackle this issue.

Related issues: #26, #27 and #28.

**Comment by paxx-dev** [comment]
This will be fixed by using option-ids

**Comment by efel85** [comment]
Can be closed as it is solved in RESTful implementation of the next pull request
