### ISSUE TITLE
Review the blueprint to ensure the definitions match coming from a TO perspective

### ISSUE THREAD

**Issue by ro5k0** [efel85/TOMP-API#35]
This is relating to the discussion that was had at the meeting on 26/06/19 with regards to the API really being for TOs to implement.

It was agreed a sub working group would go over the current blueprint from the perspective of a TO to ensure all API endpoints, schemas, and potential callbacks, made sense as a TO to implement for provision to MP.

I suggest that those who wanted to be part of this review for us to have a Slack call on 
03/07/19 at 10:00.

**Comment by brylie** [comment]
What timezone?

**Comment by ro5k0** [comment]
Sorry @brylie I presumed everyone on the project was based in CET timezone as it is a Dutch initiative.  What timezone are you based in therefore?  If others collaborators are also based in different timezone it would be good to know that as well so that when posting times we can consider people's availability.

**Comment by efel85** [comment]
Process has been started and linked to the booking state discussion in issue #9 and #41
