### ISSUE TITLE
API Documentation - Swagger Link

### ISSUE THREAD

**Issue by HimanshuGau** [efel85/TOMP-API#36]
As discussed please find below the link of API documentation:

Doc Name : Blueprint for an Application Programming Interface (API) from Transport Operator to MaaS Service Provider

API Link: https://app.swaggerhub.com/apis-docs/efel85/GTOAS/1.0.5

**Comment by ro5k0** [comment]
Any chance we can have the ability to view the swagger doc in the OpenAPI standard (format=openapi)?
