### ISSUE TITLE
Remove top level object keys

### ISSUE THREAD

**Issue by ro5k0** [efel85/TOMP-API#37]
- https://app.swaggerhub.com/apis-docs/efel85/GTOAS/1.0.5#/planning/get_free_asset_status
- https://app.swaggerhub.com/apis-docs/efel85/GTOAS/1.0.5#/operator%20information/get_station_information
- https://app.swaggerhub.com/apis-docs/efel85/GTOAS/1.0.5#/operator%20information/get_system_calendar
- https://app.swaggerhub.com/apis-docs/efel85/GTOAS/1.0.5#/operator%20information/get_system_regions

The items above in the Swagger API schemas do not need the top level key.  The endpoint should always return an array of objects relating to the endpoint to enable consistency and therefore consistent numeric lookups.

**Comment by Tjalle** [comment]
Indeed, I agree with this. There is no need for toplevel keys if the result there is only one type of object returned in the array.

**Comment by efel85** [comment]
@edwinvandenbelt will modify this in the upcoming pull request for v1.1

**Comment by edwinvandenbelt** [comment]
found some more. Now every endpoint delivers an object, that possibly contains only one array...
