### ISSUE TITLE
When using {id} as parameter in PUT/POST, it is redundant to also put it in the body.

### ISSUE THREAD

**Issue by pimmeh** [efel85/TOMP-API#38]
For instance: https://app.swaggerhub.com/apis-docs/efel85/GTOAS/1.0.6#/booking/put_bookings__id_

The {id} is given as a parameter to the endpint. Then it doesn't need to be in the JSON-body. This avoids duplication.

**Comment by drtimcooper** [comment]
If it's a response to a POST then we need to get the id somehow, don't we?  It's inconsistent if it must be in a POST response but must be taken out of a GET response.

**Comment by Tjalle** [comment]
Why is the ID needed as a parameter? I usally don't ask for ID's in the PUT/POST query params.
It can be easily retrieved from the body.

My suggestion is to remove it from the URL.

**Comment by drtimcooper** [comment]
According to REST conventions, the id is part of the URL.  You can't do a PUT if you aren't telling the server what object you're modifying.

**Comment by efel85** [comment]
@edwinvandenbelt will modify this when updating the booking part this week
