### ISSUE TITLE
CEN-NeTEx whitepaper on Flexible Transport

### ISSUE THREAD

**Issue by skinkie** [efel85/TOMP-API#43]
http://netex-cen.eu/wp-content/uploads/2015/12/07.NeTEx-Flexible-Network-and-Multimodality-WhitePaper_1.06.pdf

**Comment by ro5k0** [comment]
Unfortunately I don't see this including back-to-one as a model so perhaps we need to address this as a separate MSP flow based on the users requirements.

A lot of the current assumptions really work for people looking for a journey from Point A to Point B (potentially via a series of stop points).  This means public transport, free-floating, and back to many can all fit in to this plan.  The title says it all really, "Multi-modality"...

I think this therefore needs further discussion around how this is handled when a users requirement is to just use an asset both now and in future.

**Comment by efel85** [comment]
Added to list of links in repository
