### ISSUE TITLE
Ross big story as actual academical research

### ISSUE THREAD

**Issue by skinkie** [efel85/TOMP-API#44]
https://linkedconnections.org/

**Comment by ro5k0** [comment]
Very interesting.  I can see how this proves very useful for traditional public transport providers, and perhaps back-to-many models, to supply this data to allow for trips to be chained together.

For a back-to-one model I'd be keen to hear how you would see this being adopted given some of the MUST requirements?

I would presume that for MSPs who won't offer trip planning then this type of structure is redundant.  They would be more about booking a single type of asset at a pre-determined time and location.

Would you see the ordering of the various legs of a journey (via different transport modes) being handled by the MSP given that they specify that "It uses departure-arrival pairs from a station to another (a connection), and orders these connections by departure time"?

As a TSP we obviously wouldn't have this knowledge outside of our own system but it may be a consideration that we return the 'planned' leg of the journey in this format, when dynamic data is requested, to enable an MSP to process it in the manner above.

I feel this falls short when you deal with a back-to-one model, with no booking options and therefore no end time (such as ourselves), but welcome your thoughts on this.

**Comment by efel85** [comment]
Added to list of links in repository
