### ISSUE TITLE
Define the (generic) message header

### ISSUE THREAD

**Issue by efel85** [efel85/TOMP-API#48]
The header for all messages should be defined, and include:
- API-version (issue #29)
- Webhook to respond to for replies and validation (issue #12)

**Comment by Tjalle** [comment]
Is this meant for incoming or outgoing?
Or both?

Other usefull information might include :
Timezone, language, ..

**Comment by pimmeh** [comment]
We also need to address the authentication key. See issue #7 .

**Comment by Tjalle** [comment]
**Incoming message headers :** 
```
Accept-Language:nl   [ISO 639-1 two letter language code] 
Content-Type:application/json  [ in case of body content ]
Api-Version:1.1
Accept:application/json  
Webhook-Listener:https://www.partner.com/webhooklistener    [URL for webhook calls]
```

The `Authorization` header is mostly used for Authorization keys (Fe. Bearer -- ....)
We could also use `Authorization-Key` or something of our own choosing.
`Accept:application/json` -> this is optional, in case we would provide support for other output formats (fe. XML, ....)

**Outgoing message headers :** 
```
Content-Language:nl   [ISO 639-1 two letter language code] 
Content-Type:application/json
Api-Version:1.1
Webhook-Listener:https://www.tomp-url.nl/webhooklistener    [URL for webhook calls]
```

Usefull options : 
```
Expires:[DATE/TIME] -> for booking requests -> how long is this offer valid
Last-Modified:[DATE/TIME] -> to check when something was updated last 
Cache-Control:none   [-> or a defined time ; How long can a result be cached]
```

**Comment by pimmeh** [comment]
Can we add TOMP as a prefix to the API-version? Since we already communicate directly with TO's with different API's and so do other parties. This way we can distinguish not only the version but also the type of API.

**Comment by edwinvandenbelt** [comment]
timestamps please in UTC

**Comment by edwinvandenbelt** [comment]
In the swagger definition the webhooks are also facilitated. https://swagger.io/docs/specification/callbacks/
I'll use it in the POST of a booking-option (end state: PENDING), so it's possible to 'commit' a booking-option to a booking using PATCH /booking-options/{id} with COMMIT. Or, in case a webhook is delivered, this one must be used, but the request body should be the same as /booking-options/.

**Comment by edwinvandenbelt** [comment]
**Content-Type:application/json** is needed to let everything work. It's not explicitly mentioned in swagger.
**Webhook-Listener** is - conform the swagger default, not in the header, but in the body.
