### ISSUE TITLE
Define trip execution states

### ISSUE THREAD

**Issue by efel85** [efel85/TOMP-API#49]
This was determined as next step after the meeting on 07/08, with the goal to make a sequence diagram similar to #9.

**Comment by efel85** [comment]
![Trip Execution States](https://user-images.githubusercontent.com/23665014/63420968-10136600-c408-11e9-965c-0864ea94cbb0.png)

**Comment by efel85** [comment]
Update after meeting of 21/8, with correct depiction of alternatives:

![Trip Execution States (1)](https://user-images.githubusercontent.com/23665014/63953085-f2d23d80-ca80-11e9-9f83-f236eb8bbd06.png)

**Comment by efel85** [comment]
Trip Execution States can be exchanged to determine the phase of a specific trip for the asset. These Trip Execution States are:

PREPARING: when an asset is not yet being used by the user, but is being prepared (e.g. a taxi is coming towards the user, or a rental car is being cleaned before start of the rental).

IN USE: the user has started to use the asset. This can be acknowledged or confirmed either by the TO or MSP, depending on the type of asset.

PAUSED: if possible, an asset that is in use can be paused in order to apply a lower rate (e.g. when parked).

FINISHING: when the asset is no longer being used by the user, but the Trip execution is not yet finished (e.g. during verification of damages, cleaning of asset etc.)

ISSUE: an issue has arisen during the trip execution, reported by the user through the MSP to the TO.

FINISHED: the asset has been returned and the trip/leg is confirmed to be finished.

**Comment by JRobertoReyesG** [comment]
Update of the TRIP EXECUTION operational flow with embedded trip execution states' transition flows.

![TO-MP API blocks visualization _ 2019_09_10_TripExecution](https://user-images.githubusercontent.com/51329434/64703581-09c75580-d4ad-11e9-8dd3-fb00c192fc52.jpg)
