### ISSUE TITLE
TfNSW and many others want a "Dummies' guide to MaaS booking"

### ISSUE THREAD

**Issue by drtimcooper** [efel85/TOMP-API#52]
I'm hoping to get a document such as this:

https://docs.google.com/document/d/1KytXF3ZoTmvBHXuc7N7T3zyhDL_069uLzICZzd7e_Ms/edit?usp=sharing

If you wipe out my JSON examples and replace them with your JSON examples, then that's fine.  I just want to be able to sit down and write a reference server and client for doing MaaS bookings.

**Comment by efel85** [comment]
We discussed today that we can use the necessary updates to e.g. issues #48, #45, #9 to then easily generate the proper JSON examples for this document.

**Comment by edwinvandenbelt** [comment]
The first setup is in the [Wiki](https://github.com/efel85/TOMP-API/wiki)

**Comment by efel85** [comment]
> 
> 
> The first setup is in the [Wiki](https://github.com/efel85/TOMP-API/wiki)

@drtimcooper, would the Wiki work as a 'MaaS for dummies' guide in your opinion?

**Comment by drtimcooper** [comment]
Absolutely!   The Wiki looks fantastic & exactly what I was hoping for.  
If we close this issue, can we assume work on the wiki will continue?
And will you insert into the wiki hyperlinks to the full reference?  E.g. I'd like to know what options are available in "type-of-assert", and what value I put if it's an Uber.
