### ISSUE TITLE
Add no. of passengers in the availability-check

### ISSUE THREAD

**Issue by edwinvandenbelt** [efel85/TOMP-API#56]
The general idea is that you request f.i. 3 bikes and the service returns per asset a result. So if the TO can garantee only 2 bikes, he can deside to return an empty result or returns a result containing two seperate bikes (or bike-types).

**Comment by eborremans** [comment]
Is there a specific reason to add the number of assets the customer desires in the request? As this is an information request with no guarantees, supplying this customer info does not really seem to add anything to- nor is it needed for the result. Why not simply ask 'how many assets of type X are available on time Y?' 

In addition, if the customer is not interested in a specific - say - bike type you could optionally include a category concept that encompasses multiple asset types. The question would then be 'how many assets of category X are available on time Y?'

**Comment by edwinvandenbelt** [comment]
I think even more generic: "Which assets do you have to let X people travel from A to B on time Y?"

**Comment by pimmeh** [comment]
As requested by Roberto, an update whether this is needed for our 1.1 version or not.

I would suggest this is not needed for 1.1 but for further development of our API. A MaaS provider can simply do more than one availability request after the first booking. But, more importantly, let's first focus on actually getting our API to work for one asset first.

**Comment by edwinvandenbelt** [comment]
I think it's a pretty small adjustment (add one field). And it's a very likely scenario: "I want to travel with my family to Amsterdam...."

**Comment by Tjalle** [comment]
I think amount of passengers is a valid field to check on, especcialy on group transportation services.
In the case of single user vehicles (bikes, e-step,..) it's the amount, and that can also be important.

Where do we draw the line, I can assume we don't want to facilitate group booking (fe. a teacher seeks transport for the 25 kids in class 6B when taking a field trip).

So maybe a max of 5 would be good.
