### ISSUE TITLE
Availability-check should be usable in the routing process

### ISSUE THREAD

**Issue by edwinvandenbelt** [efel85/TOMP-API#57]
During the routing process it can be handy to already know if the TO can provide any asset (types). To do so, the availability-check should be extended to support 2 scenario's:
1) routing ( "just checking if you've got any resources" )
2) providing id's to communicate. When the id is not used in X seconds in an availibility-request to QUOTE/PEND them, it's free to use again.

I think the process should be like this: in the routing stage [finding_routes] availabilities can be checked ('just checking'). When valid routes are constructed (optionally from the returned available legs), you're entering the next stage [booking_phase]. This can be done by doing the availablity check again, but now it will return the same set, including an ID per asset (type). This ID can be used througout the process.

The user chooses an alternative (which is nothing more than a set of leg-ids). These ID's should be transactionally confirmed. This is done by starting the 'transaction' (=availability-request) and a 'commit' (=all legs have returned a asset request with an confirmation). In case one doesn't comfirm, all legs that have confirmed, should be cancelled.

![image](https://user-images.githubusercontent.com/10400054/65243782-592f0680-dae9-11e9-8d58-b46f485206d5.png)

**Comment by edwinvandenbelt** [comment]
https://cruise.eecs.uottawa.ca/umpleonline/#genArea
class MaaSPlanning {

  state {
    initial {
      // MaaS User
      enter-meta-data [not complete]-> initial;
      enter-meta-data [complete] -> finding_routes;
    }
    
    finding_routes {
      // optionally using availability-check, 'just checking'
      entry/ { createTrips(); } 
      trips_created -> booking_phase;
    }
    
    booking_phase {
      // for all distinct legs in the composed trips
      // request also ID's per leg to communicate 
      // between TO and MSP.
      availability-check-with-ids -> showing_alternatives;
    }
    
    showing_alternatives {
      choosing-alternative -> confirming_legs;
    }
    
    confirming_legs {
      // per leg, the id's from 'booking_phase' should be used
      availability-request [all_ok] -> wait_on_acks;
    }
    
    wait_on_acks {
      // the state of the booking will be 'released'
      at-least-one-denied -> initial;
      all-request-to-pending -> committing;
    }
    
    committing {
      // per leg, the id's from 'booking_phase' should be used
      asset-request [all_ok]-> confirmed;
      asset-request [error] -> initial;
    }
    
    confirmed {
      cancelling -> cancelled;
      
      trip-started -> trip_execution_phase;
      trip-preparing -> trip_execution_phase;
    }

    trip_execution_phase {
    }
  }
  
}

**Comment by JRobertoReyesG** [comment]
I see scenario 1 covered by the static information provided by TOs. And scenario 2 as part of the booking process only not of planning. This is also covered by your last update in issue #9, isn't it? Therefore, this has been already solved.
