### ISSUE TITLE
Maintainability: 1 swaggerfile instead of a lot of files

### ISSUE THREAD

**Issue by edwinvandenbelt** [efel85/TOMP-API#58]

**Comment by brylie** [comment]
This might not be necessary, if using a tool such as [DapperDox](http://dapperdox.io/). It allows multiple specifications to be integrated and cross referenced.

**Comment by edwinvandenbelt** [comment]
Brylie, DapperDox only supports swagger v2.... And doesn't allow to edit. It just shows the swagger.json in a pretty way. Am I correct?

**Comment by brylie** [comment]
Ah, I thought they had v3 support.

I'm not sure that maintaining one monolithic API spec is desirable, if the goal is for a modular, a la carte API.

What are the difficulties this issue aims to address?

**Comment by pimmeh** [comment]
In the pull request from @edwinvandenbelt I see one big Swagger file with a lot of changes we discussed. If that pull request if approved, I suggest we can close this issue.
