### ISSUE TITLE
What are stopID and stopCode?

### ISSUE THREAD

**Issue by efel85** [efel85/TOMP-API#8]
submitted by Pim van Toolen

**Comment by edwinvandenbelt** [comment]
Nice! The first national specs... Stopcode is used in the Centraal Halte Bestand... Please change it into stopID and maybe a country code?

**Comment by skinkie** [comment]
Centraal Halte Bestand defines ScheduledStopPoints (logical domain) and Quays (physical domain). The latter can be grouped by StopPlaces (single transport mode) and a Place.

In GTFS a StopID is dataset unique. Ideally this would match QuayId. In GTFS a StopCode is a big number on the stop which the traveler identifies the stop with. It is **not** a platform code. In The Netherlands I have not seen stop codes.

**Comment by edwinvandenbelt** [comment]
Hmmm. The domain model of CHB mentions 'stopplacecode'...

**Comment by skinkie** [comment]
StopPointCode (a specific position to board or alight) or StopPlaceCode (the group of stoppoints). Choose wisely what you want to represent or query.
